from .animation import Animation
from .audio import Audio
from .contact import Contact
from .dice import Dice
from .document import Document
from .file import File
from .game import Game
from .maskposition import MaskPosition
from .messageentity import MessageEntity
from .photosize import PhotoSize
from .poll import Poll
from .polloption import PollOption
from .sticker import Sticker
from .venue import Venue
from .video import Video
from .videonote import VideoNote
from .voice import Voice
